//
// Copyright (c) 2016-2018 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

== Architecture


This chapter describes the architectural overview of how metrics are setup, stored and exposed for consumption.
This chapter also lists the various scopes of metrics.

See section <<required-metrics>> for more information regarding metrics that are required for each vendor.

See section <<app-metrics-api>> for more information regarding the application metrics programming model.

[[metrics-setup]]
=== Metrics Setup

Metrics that are exposed need to be configured in the server. On top of the pure metrics, metadata needs to be provided.

The following three sets of sub-resource (scopes) are exposed.

* base: metrics that all MicroProfile vendors have to provide
* vendor: vendor specific metrics (optional)
* application: application-specific metrics (optional)

NOTE: It is expected that a future version of this specification will also have a sub-resource for integrations
with other specifications of MicroProfile.

[[scopes]]
==== Scopes

===== Required Base metrics

Required base metrics describe a set of metrics that all MicroProfile-compliant servers have to provide.
Each vendor can implement the set-up of the metrics in the _base_ scope in a vendor-specific way.
The metrics can be hard coded into the server or read from a configuration file or supplied via the Java-API described in <<app-metrics-api>>.
The Appendix shows a possible data format for such a configuration.
The configuration and set up of the _base_ scope is thus an implementation detail and is not expected to be portable across vendors.

Section <<required-metrics>> lists the required metrics. This list also includes a few items marked as optional.
These are listed here as they are dependent on the underlying JVM and not the server and thus fit better in _base_ scope
than the _vendor_ one.

Required base metrics are exposed under `/metrics/base`.

===== Application metrics

Application specific metrics can not be baked into the server as they are supposed to be provided by the
application at runtime. Therefore a Java API is provided. Application specific metrics are supposed to be
portable to other implementations of the MicroProfile. That means that an application written to this
specification which exposes metrics, can expose the same metrics on a different compliant server
without change.

Details of this Java API are described in <<app-metrics-api>>.

Application specific metrics are exposed under `/metrics/application`.


===== Vendor specific Metrics

It is possible for MicroProfile server implementors to supply their specific metrics data on top
of the basic set of required metrics.
Vendor specific metrics are exposed under `/metrics/vendor`.

Examples for vendor specific data could be metrics like:

* OSGi statistics if the MicroProfile-enabled container internally runs on top of OSGi.
* Statistics of some internal caching modules

Vendor specific metrics are not supposed to be portable between different implementations
of MicroProfile servers, even if they are compliant with the same version of this specification.

[[supplying_of_tags]]
==== Supplying of Tags

Tags (or labels) play an important role in modern microservices and microservice scheduling systems (like e.g. Kubernetes).
Application code can run on any node and can be re-scheduled to a different node at any time. Each container in such
an environment gets its own ID; when the container is stopped and a new one started for the same image, it will get a
different id. The classical mapping of host/node and application runtime on it, therefore no longer works.

Tags have taken over the role to, for example, identify an application (`app=myShop`), the tier inside the application
(`tier=database` or `tier=app_server`) and also the node/container id. Aggregation of metrics can then work over label
queries (Give me the API hit count for `app=myShop && tier=app_server`).

In MicroProfile Metrics, tags add an additional dimension to metrics that share a common basis. For example, a metric named
`carCount` can be further differentiated by the car type (sedan, SUV, coupe, and etc) and the colour (red, blue, white, black,
and etc). Rather than incorporating this in the metric name, tags can be used to capture these information in separate metrics.

[source]
```
carCount{type=sedan,colour=red}
carCount{type=sedan,colour=blue}
carCount{type=suv,colour=red}
carCount{type=coupe,colour=blue}
```

The key name for the tag must match the regex `[a-zA-Z_][a-zA-Z0-9_]*` (Ascii alphabet, numbers and underscore). If an illegal character is
used, the implementation must throw an IllegalArgumentException.

The tag value may contain any Unicode character.

Tags can be supplied in two ways:

* At the level of a metric as described in <<app-metrics-api>>.
* At the application server level by using https://github.com/eclipse/microprofile-config[MicroProfile Config] and
setting a property of the name `MP_METRICS_TAGS`.
This property translates to the environment variable `MP_METRICS_TAGS`.

NOTE: The use of MicroProfile-Config is mandatory in MicroProfile-Metrics 1.1 even if it only serves to provide
the global tags that existed already in Metrics 1.0. Future version of the spec will introduce more config options.

.Set up global tags via environment
[source,bash]
----
export MP_METRICS_TAGS=app=shop,tier=integration
----

Global tags and tags set in metric metadata are included in the output returned from the REST API.

[[meta-data-def]]
==== Metadata

Metadata can be specified for metrics in any scope. For base metrics, metadata must be provided by the implementation. Metadata is exposed by the REST handler.

TIP: While technically it is possible to expose metrics without (some) of the metadata, it helps tooling and also
operators when correct metadata is provided, as this helps getting a context and an explanation of the metric.

The Metadata:

* name: The name of the metric.
* unit: a fixed set of string units
* type:
** counter: an incrementally increasing or decreasing numeric value (e.g. total number of requests received or total number of concurrently active HTTP sessions).
** gauge: a metric that is sampled to obtain its value (e.g. cpu temperature or disk usage).
** meter: a metric which tracks mean throughput and one-, five-, and fifteen-minute exponentially-weighted moving average throughput.
** histogram: a metric which calculates the distribution of a value.
** timer: a metric which aggregates timing durations and provides duration statistics, plus throughput statistics.
* description (optional): A human readable description of the metric.
* displayName (optional): A human readable name of the metric for display purposes if the metric name is not
human readable. This could e.g. be the case when the metric name is a uuid.
* tags (optional): A list of `key=value` pairs, which are separated by comma. See also <<supplying_of_tags>>.
* reusable (optional): If set to `true`, then it is allowed to register a metric multiple times under the same name.
Note that all such instances must set `reusable` to `true`.
Default is `false`.
See <<reusing_of_metrics>> for more details.

Metadata must not change over the lifetime of a process (i.e. it is not allowed
to return the units as seconds in one retrieval and as hours in a subsequent one).
The reason behind it is that e.g. a monitoring agent on Kubernetes may read the
metadata once it sees the new container and store it. It may not periodically
re-query the process for the metadata.

IMPORTANT: In fact, metadata should not change during the life-time of the
whole container image or an application, as all containers spawned from it
will be "the same" and form part of an app, where it would be confusing in
an overall view if the same metric has different metadata.

=== Metric Registry
The `MetricRegistry` stores the metrics and metadata information.
There is one `MetricRegistry` instance for each of the scopes listed in <<scopes>>.

Metrics can be added to or retrieved from the registry either using the `@Metric` annotation
(see <<api-annotations, Metrics Annotations>>) or using the `MetricRegistry` object directly.

A metric is uniquely identified by the `MetricRegistry` if the combination of the name and tags (order independent) in the Metadata are unique.
However, all metrics of the same name must be of the same type otherwise an `IllegalArgumentException` will be thrown.

[[reusing_of_metrics]]
==== Reusing of Metrics

By default it is not allowed to re-register more than one metric under a certain name and tags combination in a scope. This is done
to prevent hard to spot copy & paste errors, where for example all methods of a Jax-Rs class are marked with
`@Timed(name="myApp", absolute=true)`.

If this behaviour is required, then it is possible to mark all such instances as _reusable_ by passing
the respective flag via Metadata or field in the Annotation. Gauges are not reusable.

The implementation must throw an 'IllegalArgumentException' during a metric registration call when the call would result
in the reuse of a metric where that metric was either previously declared not reusable or where the registration call itself
declares the metric to not be reusable.

Only metrics of the same type can be reused under the same name.
Trying to reuse a name for different types will result in an `IllegalArgumentException`.

TIP: If you want to re-use a metric name, then you need to also explicitly set the `name` field OR set `absolute`
to `true` and have multiple methods annotated as metric that have the same method name.

.Example of reused counters
[source,java]
----
    @Counted(name = "countMe", absolute = true, reusable = true)
    public void countMeA() { }

    @Counted(name = "countMe", absolute = true, reusable = true)
    public void countMeB() { }
----

In the above examples both `countMeA()` and `countMeB()` will share a single Counter with registered name `countMe` in application scope.

[[rest-api]]
=== Exposing metrics via REST API

Data is exposed via REST over HTTP under the `/metrics` base path in two different data formats for `GET` requests:

* JSON format - used when the HTTP Accept header matches `application/json`.
* Prometheus text format - default response format when the HTTP Accept header does not match any more specific
media type like `application/json`.
+
NOTE: Future versions may allow for more export formats that are triggered by their specific media type. The Prometheus
text format will stay as fall-back.

Formats are detailed below.

Data access must honour the HTTP response codes, especially

* 200 for successful retrieval of an object
* 204 when retrieving a subtree that would exist, but has no content. E.g. when the application-specific subtree has no application specific metrics defined.
* 404 if a directly-addressed item does not exist. This may be a non-existing sub-tree or non-existing object
* 406 if the HTTP Accept Header in the request cannot be handled by the server.
* 500 to indicate that a request failed due to "bad health". The body SHOULD contain details if possible { "details": <text> }

The API MUST NOT return a 500 Internal Server Error code to represent a non-existing resource.

.Supported REST endpoints
[cols="2,1,1,3"]
|===
| Endpoint | Request Type | Supported Formats | Description

| `/metrics` | GET | JSON, Prometheus | Returns all registered metrics
| `/metrics/<scope>` | GET | JSON, Prometheus | Returns metrics registered for the respective scope. Scopes are listed in <<metrics-setup>>
| `/metrics/<scope>/<metric_name>` | GET | JSON, Prometheus | Returns the metric that matches the metric name for the respective scope
| `/metrics` | OPTIONS | JSON | Returns all registered metrics' metadata
| `/metrics/<scope>` | OPTIONS | JSON | Returns metrics' metadata registered for the respective scope. Scopes are listed in <<metrics-setup>>
| `/metrics/<scope>/<metric_name>` | OPTIONS | JSON | Returns the metric's metadata that matches the metric name for the respective scope
|===

NOTE: The implementation must return a 406 response code if the request's HTTP Accept header for an OPTIONS request
does not match `application/json`.
