//
// Copyright (c) 2016-2018 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

=== Major changes to previous versions

* Since 1.1
** Removed unnecessary `@InterceptorBinding` annotation from `org.eclipse.microprofile.metrics.annotation.Metric`.
** Removed deprecated `org.eclipse.microprofile.metrics.MetricRegistry.register(String name, Metric, Metadata)`
** `Metadata` is now immutable and built via a `MetadataBuilder`.
** Introduced a Tag object which represents a singular tag key/value pair.
** Metrics are now uniquely identified by a MetricID (combination of the metric's name and tags).
** The 'Metadata' is mapped to a unique metric name in the `MetricRegistry` and this relationship is immutable.
** Tag key names are restricted to match the regex `[a-zA-Z_][a-zA-Z0-9_]*`.
** Tag values defined through MP_METRICS_TAGS must escape equal signs `=` and commas `,` with a backslash `\`.
** JSON format for GET requests now includes tags along with the metric name. JSON format for OPTIONS requests
have been modified such that the 'tags' attribute is a list of nested lists which holds tags from different metrics that
 are associated with the metadata.
** Reserved characters in Prometheus format must be escaped.


* Since 1.0
** Improved TCK
** `org.eclipse.microprofile.metrics.MetricRegistry.register(String name, Metric, Metadata)` is deprecated.
Use `org.eclipse.microprofile.metrics.MetricRegistry.register(Metadata, Metric)` instead, where `Metadata`
already has a field for the name.
** Global tags are now supplied via the means of MicroProfile Config (the env variable is still valid).
** Annotations and `Metadata` can now have a flag `reusable` that indicates that the metric name can be registered
more than once. Default is `false` as in Metrics 1.0. See <<reusing_of_metrics>>.
