//
// Copyright (c) 2016-2018 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//

== Major changes to previous versions

Changes marked with icon:bolt[role="red"] are breaking changes relative to previous versions of the spec.

* Changes in 2.2
** Reverted a problematic change from 2.1 where Gauges were required to return subclasses of `java.lang.Number` 
** (2.2.1) Added ProcessCpuTime as a new optional base metric.

* Changes in 2.1
** Clarified that metric registry implementations are required to be thread-safe.
** Clarified in the API code that Gauges must return values that extend `java.lang.Number`. [NOTE: this caused issues with backward compatibility and was reverted in 2.2]
** Clarified that implementations can, for JSON export of scopes containing no metrics, omit them, or that they can be present with an empty value. 
** TCKs are updated to use RestAssured 4.0
** Added the `reusable(boolean)` method for MetadataBuilder 
** Explicitly excluded the transitive dependency on `javax.el-api` from the build of the specification. It wasn't actually used anywhere in the build so there should be no impact. 
Implementations can still support the Expression Language if they choose to.  
** Added some text to the specification about programmatic creation of metrics (without annotations)

* Changes in 2.0
** icon:bolt[role="red"] Refactoring of Counters, as the old `@Counted` was misleading in practice.
*** Counters via `@Counted` are now always monotonic, the `monotonic` attribute is gone.
The `Counted` interface lost the `dec()` methods.
*** Former non-monotonic counters are now <<app-programming-model#ConcurrentGaugeDef,`@ConcurrentGauge`>> and also in the output reported as gauges.
*** See <<appendix#migration-hint-to-20, Migration hints>> about migration of applications using MicroProfile Metrics.
** Removed unnecessary `@InterceptorBinding` annotation from `org.eclipse.microprofile.metrics.annotation.Metric`.
** icon:bolt[role="red"] Removed deprecated `org.eclipse.microprofile.metrics.MetricRegistry.register(String name, Metric, Metadata)`
** icon:bolt[role="red"]  `Metadata` is now immutable and built via a <<app-programming-model#pgm-metadata,`MetadataBuilder`>>.
** Introduced a Tag object which represents a singular tag key/value pair.
** icon:bolt[role="red"] Metrics are now uniquely identified by a <<architecture#metricid-data-def,MetricID>> (combination of the metric's name and tags).
** MetricFilter modified to filter with MetricID instead of name
** The 'Metadata' is mapped to a unique metric name in the `MetricRegistry` and this relationship is immutable.
** Tag key names for labels are restricted to match the regex `[a-zA-Z_][a-zA-Z0-9_]*`.
** Tag values defined through MP_METRICS_TAGS must escape equal signs `=` and commas `,` with a backslash `\`.
** icon:bolt[role="red"] <<rest-endpoints#json-format-def,JSON output format>> for GET requests now appends tags along with the metric in `metricName;tag=value;tag=value` format.
JSON format for OPTIONS requests have been modified such that the 'tags' attribute is a list of nested lists which holds tags from different metrics that
 are associated with the metadata.
** OpenMetrics format - formerly called Prometheus format
*** Reserved characters in OpenMetrics format must be escaped.
*** icon:bolt[role="red"] In OpenMetrics output format, the separator between scope and metric name is now a `_` instead of a `:`.
*** icon:bolt[role="red"] Metric names with camelCase are no longer converted to snake_case for OpenMetrics output.
** icon:bolt[role="red"] The default value of the `reusable` attribute for metric objects created programmatically (not via annotations) is now `true`
** icon:bolt[role="red"] Some base metrics' names have changed to follow the convention of ending the name of accumulating counters with `total`.
** icon:bolt[role="red"] Some base metrics' types have changed from Counter to Gauge since Counters must now count monotonically.
** icon:bolt[role="red"] Some base metrics' names have changed because they now use tags to distinguish metrics for multiple JVM objects. For example,
each existing garbage collector now has its own `gc.total` metric with the name of the garbage collector being in a tag. Names
of some base metrics in the OpenMetrics output are also affected by the removal of conversion from camelCase to snake_case.
** Added a set of recommendations how application servers with multiple deployed applications should behave if they support MP Metrics.

* Changes in 1.1
** Improved TCK
** `org.eclipse.microprofile.metrics.MetricRegistry.register(String name, Metric, Metadata)` is deprecated.
Use `org.eclipse.microprofile.metrics.MetricRegistry.register(Metadata, Metric)` instead, where `Metadata`
already has a field for the name.
** Global tags are now supplied via the means of MicroProfile Config (the env variable is still valid).
** Annotations and `Metadata` can now have a flag `reusable` that indicates that the metric name can be registered
more than once. Default is `false` as in Metrics 1.0. See <<architecture#reusing_metrics>>.
