//
// Copyright (c) 2016-2017 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//


:sectanchors:
:doctype: book
:license: Apache License v2.0
:source-highlighter: coderay
:authors: Heiko W. Rupp, Raymond Lam, David Chan
:email: hrupp@redhat.com, lamr@ca.ibm.com, chdavid@ca.ibm.com
ifdef::backend-pdf[]
:pagenums:
endif::[]
:doctype: book
:revnumber: 1.0
:revdate: 2017-08-22
:revremark: Proposal
:toc: left
:toclevels: 4
:sectnums:

= Metrics for Eclipse Microprofile

include::license-alv2.asciidoc[]

== Introduction

To ensure reliable operation of the software it is necessary to monitor essential
system parameters. This enhancement proposes the addition of well-known monitoring
endpoints and metrics for each process adhering to the Eclipse Microprofile standard.

This proposal does not talk about health checks. There is a separate specification for
https://github.com/eclipse/microprofile-health[Health Checks].

=== Motivation

Reliable service of a platform needs monitoring. There is already JMX as
standard to expose metrics, but remote-JMX is not easy to deal with and
especially does not fit well in a polyglot environment where other services
are not running on the JVM.
To enable monitoring in an easy fashion it is necessary that all Microprofile
implementations follow a certain standard with respect to (base) API path,
data types involved, always available metrics and return codes used.

=== Difference to health checks

Health checks are primarily targeted at a quick yes/no response to the
question "Is my application still running ok?". Modern systems that
schedule the starting of applications (e.g. Kubernetes) use this
information to restart the application if the answer is 'no'.

Metrics on the other hand can help to determine the health. Beyond this
they serve to pinpoint issues, provide long term trend data for capacity
planning and pro-active discovery of issues (e.g. disk usage growing without bounds).
Metrics can also help those scheduling systems to make decisions when to scale the application
to run on more or less machines depending on the metrical values.


== Architecture


This chapter describes the architectural overview of how metrics are setup, stored and exposed for consumption.
This chapter also lists the various scopes of metrics.

See section <<required-metrics>> for more information regarding metrics that are required for each vendor.

See section <<app-metrics-api>> for more information regarding the application metrics programming model.

[[metrics-setup]]
=== Metrics Setup

Metrics that are exposed need to be configured in the server. On top of the pure metrics, metadata needs to be provided.

The following three sets of sub-resource (scopes) are exposed.

* base: metrics that all Microprofile vendors have to provide
* vendor: vendor specific metrics (optional)
* application: application-specific metrics (optional)

NOTE: It is expected that a future version of this specification will also have a sub-resource for integrations
with other specifications of Microprofile.

==== Scopes

===== Required Base metrics

Each vendor of a Microprofile-compliant server can implement setting up the metrics in the _base_ scope in a
vendor-specific way.
The metrics can be hard coded into the server or read from a configuration file or supplied via the Java-API described in <<app-metrics-api>>.
The Appendix shows a possible data format for such a configuration.
The configuration and set up of the _base_ scope is an implementation detail and is not expected to be portable across vendors.

Section <<required-metrics>> lists the required metrics. This list also includes a few items marked as optional.
These are listed here as they are dependent on the underlying JVM and not the server and thus fit better in _base_ scope
than the _vendor_ one.

===== Application metrics

Application specific metrics can not be backed into the server as they are supposed to be provided by the
application at runtime. Therefore a Java API is provided. Application specific metrics are supposed to be
portable to other implementations of the Microprofile. That means that an application written to this
specification which exposes metrics, can expose the same metrics on a different compliant server
without change.

Details of this Java API are described in <<app-metrics-api>>.

Application specific metrics are exposed under `/metrics/application`.


===== Vendor specific Metrics

It is possible for Microprofile server implementors to supply their specific metrics data on top
of the basic set of required metrics.
Vendor specific metrics are exposed under `/metrics/vendor`.

Examples for vendor specific data could be metrics like:

* OSGi statistics if the Microprofile-enabled container internally runs on top of OSGi.
* Statistics of some internal caching modules

Vendor specific metrics are not supposed to be portable between different implementations
of Microprofile servers, even if they are compliant with the same version of this specification.


==== Supplying of Tags

Tags (or labels) play an important role in modern microservices and microservice scheduling systems (like e.g. Kubernetes).
Application code can run on any node and can be re-scheduled to a different node at any time. Each container in such
an environment gets its own ID; when the container is stopped and a new one started for the same iamge, it will get a
different id. The classical mapping of host/node and application runtime on it, therefore no longer works.

Tags have taken over the role to for example identify an application (`app=myShop`), the tier inside the application
(`tier=database` or `tier=app_server`) and also the node/container id. Aggregation of metrics can then work over label
queries (Give me the API hit count for `app=myShop && tier=app_server`).

Tags can be supplied in two ways:

* At the level of a metric as described in <<app-metrics-api>>.
* At the application server level by passing the list of tags in an environment variable `MP_METRICS_TAGS`.

.Set up global tags
[source,bash]
----
export MP_METRICS_TAGS=app=shop,tier=integration
----

Global tags will be appended to the per-metric tags.

[[meta-data-def]]
==== Metadata

For all exposed metrics, matching metadata is exposed and needs to be provided by the setup. This is true for all scopes.

* unit: a fixed set of string units
* type:
** counter: a monotonically increasing or decreasing numeric value (e.g. total number of requests received)
** gauge: a numeric value that can arbitrarily go up and down (e.g. cpu or disk usage)
** meter: a metric which measures mean throughput and one-, five-, and fifteen-minute exponentially-weighted moving average throughputs
** histogram: a metric which calculates the distribution of a value
** timer: A timer metric which aggregates timing durations and provides duration statistics, plus  throughput statistics via
* description (optional): A human readable description of the metric
* displayName (optional): A human readable name of the metric for display purposes if the metric name is not
human readable. This could e.g. be the case when the metric name is a uuid.
* tags (optional): A list of `key=value` pairs, which are separated by comma. See also <<_supplying_of_tags>>.

Metadata must not change over the lifetime of a process (i.e. it is not allowed
to return the units as seconds in one retrieval and as hours in a subsequent one).
The reason behind it is that e.g. a monitoring agent on Kubernetes may read the
metadata once it sees the new container and store it. It may not periodically
re-query the process for the metadata.

NOTE:: In fact, metadata should not change during the life-time of the
whole container image or an application, as all containers spawned from it
will be "the same" and form part of an app, where it would be confusing in
an overall view if the same metric has different metadata.

=== Metric Registry
<TO DO>

=== Exposing metrics via REST API

Data is exposed via REST over http under the `/metrics` base path in two default data formats for `GET` requests:

* Json format.
* Prometheus text format.

Formats are detailed below.

Data access must honour the http response codes, especially

* 200 for successful retrieval of an object
* 204 when retrieving a subtree that would exist, but has no content. E.g. when the application-specific subtree has no application specific metrics defined.
* 404 if an directly-addressed item does not exist. This may be a non-existing sub-tree or non-existing object
* 500 to indicate that a request failed due to "bad health". The body SHOULD contain details if possible { "details": <text> }

The Api MUST NOT return a 500 Internal Server Error code to represent a non-existing resource.

Accessing `/metrics` will return all registered metrics.

Accessing `/metrics/<scope>` will only return metrics registered for the respective scope. Scopes are listed in <<metrics-setup>>.


==== JSON format

* Metrics will respond to GET requests and are exposed in a tree like fashion with sub-trees for the sub-resources mentioned in the previous section.
A sub-tree that does not contain data can be omitted.
* A 'shadow tree' that responds to OPTIONS will provide the metadata.

*REST-Api Objects*

Api-objects MAY include one or more metrics as in

[source,json]
----
{
  "thread-count" : 33,
  "peak-thread-count" : 47,
  "total-started-thread-count" : 49,
  "current-thread-cpu-time" : 66855000,
  "current-thread-user-time" : 64003000
}
----

or

[source]
----
{
  "count": 45
}
----

In case `/metrics` is requested, then the data for the scopes are wrapped in the scope name:

[source,javascript]
----
{
  "base": {
     "thread-count" : 33,
     "peak-thread-count" : 47,
  },
  "vendor": [...]
}
----

*Metadata*


Metadata is exposed in a tree-like fashion with sub-trees for the sub-resources mentioned previously.
The same wrapping of scopes applies as for metrics.

Example:

If `GET /metrics/base/fooVal` exposes:

[source]
----
{"fooVal": 12345}
----

then `OPTIONS /metrics/base/fooVal` will expose:

[source]
----

{
  "fooVal": {
    "unit": "ms",
    "type": "gauge",
    "description": "The size of foo after each request",
    "displayName": "Size of foo",
    "tags": "app=webshop"
  }
}

----

If `GET /metrics/base` exposes multiple values like this:

.Example of exposed metrics data
[source]
----
{
  "fooVal": 12345,
  "barVal": 42
}
----

then `OPTIONS /metrics/base` exposes:

.Example of Json output of Metadata
[source]
----
{
  "fooVal": {
    "unit": "ms",
    "type": "gauge",
    "description": "The duration of foo after each request",
    "displayName": "Duration of foo",
    "tags": "app=webshop"
  },
  "barVal": {
    "unit": "mbytes",
    "type": "gauge",
    "tags": "component=backend,app=webshop"
  }
}
----


==== Prometheus format

Data is exposed in text format as described in
https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details[Prometheus text format] when
the GET request asks for `text/plain` encoding.

The metadata will be included inline in the Prometheus text format, specified by it.

TIP: Users that want to write tools to transform the metadata can still request the metadata via OPTIONS
request and json media type.

The above json example would look like this in Prometheus format

.Example of Prometheus output
[source]
----
# TYPE base:foo_val_seconds gauge   <1>
# HELP base:foo_val_seconds The duration of foo after each request <2>
base:foo_val_seconds{app="webshop"} 12.345  <3>
# TYPE base:bar_val_bytes gauge <1>
base:bar_val_bytes{component="backend", app="webshop"} 42000 <3>
----
<1> Metric names are turned from camel case into snake_case.
<2> The description goes into the HELP line
<3> Metric names gets the base unit of the family appended with `_` and defined labels. Values are scaled accordingly

===== Translation rules for metric names

Prometheus text format does not allow for all characters and adds the base unit of a family to the name.

* Dot (`.`), Space (` `), Dash (`-`) are translated to underscore (`_`).
* Scope is always starts the metric name.
* Scope and name are separated by colon (`:`).
* camelCase is translated to camel_case
* Double underscore is translated to single underscore
* Colon-underscore (`:_`) is translated to single colon
* The unit is appended to the name, separated by underscore. See also below.


===== Handling of tags

Metric tags are appended to the metric name in curly braces `{` and `}` and are separated by comma.
Each tag is a key-value-pair in the format of `<key>="<value>"`.

===== Handling of units

Units are appended as the base unit of the respective family. Metric values are scaled accordingly.

Unit families and their base units are described under https://prometheus.io/docs/practices/naming/#base-units[Prometheus metric names, Base units].

Families and Prometheus base units are:

|===
| Family | Base unit

| Bit    | bytes
| Byte   | bytes
| Time   | seconds
| Percent | ratio (normally ratio is A_per_B, but there are exceptions like `disk_usage_ratio`)
|===

==== Security

It must be possible to secure the endpoints via the usual means. The definition of 'usual means' is in
this version of the specification implementation specific.

In case of a secured endpoint, accessing `/metrics` without valid credentials must return a `401 Unauthorised` header.

A server SHOULD implement TLS encryption by default.

It is allowed to ignore security for trusted origins (e.g. localhost)


[[required-metrics]]
== Required Metrics

Base metrics is a list of metrics that all vendors need to implement. Optional base metrics are recommended to be implemented but are not required.
These metrics are exposed under `/metrics/base`.

The following is a list of required and optional base metrics. All metrics have Multi: false unless otherwise stated.
Visit <<meta-data-def>> for the meaning of each key

Values from the MBean server are encoded with `MBean-Name/attribute[#field]` name to retrieve a single attribute.
E.g. `GET /metrics/base/java.lang:type=Memory/ObjectPendingFinalizationCount` to only get that count.
For MBeans attributes that are of type `CompositeData`, the `#field` will return a single item of this composite
data.


=== General JVM Stats

*UsedHeapMemory*
[cols="1,4"]
|===
|Name| usedHeapMemory
|DisplayName| Used Heap Memory
|Type| Gauge
|Unit| Bytes
|Description| Displays the amount of used heap memory in bytes.
|MBean| java.lang:type=Memory/HeapMemoryUsage#used
|===

*CommittedHeapMemory*
[cols="1,4"]
|===
|Name| committedHeapMemory
|DisplayName| Committed Heap Memory
|Type| Gauge
|Unit| Bytes
|Description| Displays the amount of memory in bytes that is committed for the Java virtual machine to use. This amount of memory is guaranteed for the Java virtual machine to use.
|MBean| java.lang:type=Memory/HeapMemoryUsage#committed
|Notes| Also from JSR 77
|===

*MaxHeapMemory*
[cols="1,4"]
|===
|Name| maxHeapMemory
|DisplayName| Max Heap Memory
|Type| Gauge
|Unit| Bytes
|Description| Displays the maximum amount of heap memory in bytes that can be used for memory management. This attribute displays -1 if the maximum heap memory size is undefined. This amount of memory is not guaranteed to be available for memory management if it is greater than the amount of committed memory. The Java virtual machine may fail to allocate memory even if the amount of used memory does not exceed this maximum size.
|MBean| java.lang:type=Memory/HeapMemoryUsage#max
|===

*GCCount*
[cols="1,4"]
|===
|Name| gc.%s.count
|DisplayName| Garbage Collection Count
|Type| Counter
|Unit| None
|Multi| true
|Description|  Displays the total number of collections that have occurred. This attribute lists -1 if the collection count is undefined for this collector.
|MBean| java.lang:type=GarbageCollector,name=%s/CollectionCount
|Notes| There can be multiple garbage collectors active that are assigned to different memory pools. The %s should be substituted with the name of the garbage collector.
|===

*GCTime - Approximate accumulated collection elapsed time in ms*
[cols="1,4"]
|===
|Name| gc.%s.time
|DisplayName| Garbage Collection Time
|Type| Counter
|Unit| Milliseconds
|Multi| true
|Description| Displays the approximate accumulated collection elapsed time in milliseconds. This attribute displays -1 if the collection elapsed time is undefined for this collector. The Java virtual machine implementation may use a high resolution timer to measure the elapsed time. This attribute may display the same value even if the collection count has been incremented if the collection elapsed time is very short.
|MBean| java.lang:type=GarbageCollector,name=%s/CollectionTime
|Notes| There can be multiple garbage collectors active that are assigned to different memory pools. The %s should be substituted with the name of the garbage collector.
|===

*JVM Uptime - Up time of the Java Virtual machine*
[cols="1,4"]
|===
|Name| jvmUptime
|DisplayName| JVM Uptime
|Type| Counter
|Unit| Milliseconds
|Description| Displays the start time of the Java virtual machine in milliseconds. This attribute displays the approximate time when the Java virtual machine started.
|MBean| java.lang:type=Runtime/Uptime
|Notes| Also from JSR 77
|===

=== Thread JVM Stats

*ThreadCount*
[cols="1,4"]
|===
|Name| threadCount
|DisplayName| Thread Count
|Type| Gauge
|Unit| None
|Description| Displays the current number of live threads including both daemon and non-daemon threads
|MBean| java.lang:type=Threading/ThreadCount
|===

*DaemonThreadCount*
[cols="1,4"]
|===
|Name| daemonThreadCount
|DisplayName| Daemon Thread Count
|Type| Gauge
|Unit| None
|Description| Displays the current number of live daemon threads.
|MBean| java.lang:type=Threading/DaemonThreadCount
|===

*PeakThreadCount*
[cols="1,4"]
|===
|Name| peakThreadCount
|DisplayName| Peak Thread Count
|Type| Counter
|Unit| None
|Description| Displays the peak live thread count since the Java virtual machine started or peak was reset. This includes daemon and non-daemon threads.
|MBean| java.lang:type=Threading/PeakThreadCount
|===

=== Thread Pool Stats

*(Optional) ActiveThreads*
[cols="1,4"]
|===
|Name| threadPool.%s.activeThreads
|DisplayName| Active Threads
|Type| Gauge
|Unit| None
|Multi| true
|Description| Number of active threads that belong to a specific thread pool.
Note: The %s should be substituted with the name of the thread pool. This is a vendor specific attribute/operation that is not defined in java.lang.
|===

*(Optional) PoolSize*
[cols="1,4"]
|===
|Name| threadPool.%s.size
|DisplayName| Thread Pool Size
|Type| Gauge
|Unit| None
|Multi| true
|Description| The size of a specific thread pool.
Note: The %s should be substituted with the name of the thread pool. This is a vendor specific attribute/operation that is not defined in java.lang.
|===

=== ClassLoading JVM Stats

*LoadedClassCount*
[cols="1,4"]
|===
|Name| currentLoadedClassCount
|DisplayName| Current Loaded Class Count
|Type| Gauge
|Unit| None
|Description| Displays the number of classes that are currently loaded in the Java virtual machine.
|MBean| java.lang:type=ClassLoading/LoadedClassCount
|===

*TotalLoadedClassLoaded*
[cols="1,4"]
|===
|Name| totalLoadedClassCount
|DisplayName| Total Loaded Class Count
|Type| Counter
|Unit| None
|Description| Displays the total number of classes that have been loaded since the Java virtual machine has started execution.
|MBean| java.lang:type=ClassLoading/TotalLoadedClassCount
|===

*UnloadedClassCount*
[cols="1,4"]
|===
|Name| totalUnloadedClassCount
|DisplayName| Total Unloaded Class Count
|Type| Counter
|Unit| None
|Description| Displays the total number of classes unloaded since the Java virtual machine has started execution.
|MBean|java.lang:type=ClassLoading/UnloadedClassCount
|===

=== Operating System

*AvailableProcessors*
[cols="1,4"]
|===
|Name| availableProcessors
|DisplayName| Available Processors
|Type| Gauge
|Unit| None
|Description| Displays the number of processors available to the Java virtual machine. This value may change during a particular invocation of the virtual machine.
|MBean| java.lang:type=OperatingSystem/AvailableProcessors
|===

*SystemLoadAverage*
[cols="1,4"]
|===
|Name| systemLoadAverage
|DisplayName| System Load Average
|Type| Gauge
|Unit| None
|Description| Displays the system load average for the last minute. The system load average is the sum of the number of runnable entities queued to the available processors and the number of runnable entities running on the available processors averaged over a period of time. The way in which the load average is calculated is operating system specific but is typically a damped time-dependent average. If the load average is not available, a negative value is displayed. This attribute is designed to provide a hint about the system load and may be queried frequently. The load average may be unavailable on some platform where it is expensive to implement this method.
|MBean| java.lang:type=OperatingSystem/SystemLoadAverage
|===

*(Optional) ProcessCpuLoad*
[cols="1,4"]
|===
|Name| processCpuLoad
|DisplayName| Process CPU Load
|Type| Gauge
|Unit| Percent
|Description| Displays the "recent cpu usage" for the Java Virtual Machine process
|MBean| java.lang:type=OperatingSystem (com.sun.management.UnixOperatingSystemMXBean for Oracle Java, similar one exists for IBM Java: com.ibm.lang.management.ExtendedOperatingSystem)
Note: This is a vendor specific attribute/operation that is not defined in java.lang
|===



[[app-metrics-api]]
== Application Metrics Programming Model

<paragarph describing what this chapter is about>

=== Annotations
<TO DO>

=== Metric Registry
<TO DO>

=== Java API Classes

==== Metadata

[source]
----
/**
 * Bean holding the metadata of one single metric
 */
@SuppressWarnings("unused")
public class MetadataEntry {

  /**
   * Name of the metric.
   * <p>Exposed over REST</p>
   */
  private String name;
  /**
   * Display name of the metric. If not set, the name is taken.
   * <p>Exposed over REST</p>
   */
  private String displayName;
  /**
   * The mbean info to retrieve the data from.
   * Format is objectname/attribute[#field], with field
   * being one field in a composite attribute.
   * E.g. java.lang:type=Memory/HeapMemoryUsage#max
   */
  @JsonIgnore
  private String mbean;
  /**
   * A human readable description.
   * <p>Exposed over REST</p>
   */
  private String description;
  /**
   * Type of the metric.
   * <p>Exposed over REST</p>
   */
  private MpMType type;
  /**
   * Unit of the metric.
   * <p>Exposed over REST</p>
   */
  private MpMUnit unit;
  /**
   * Tags of the metric. Augmented by global tags.
   * <p>Exposed over REST</p>
   */
  @JsonInclude(JsonInclude.Include.NON_NULL)
  private String tags;

  public MetadataEntry(String name, MpMType type, MpMUnit unit) {
    this.name = name;
    this.type = type;
    this.unit = unit;
  }

[...]
}
----

==== Metric type

[source]
----
public enum MpMType {
  /**
   * A Counter monotonically in-/decreases its values.
   * An example could be the number of Transactions committed.
    */
  COUNTER("counter"),
  /**
   * A Gauge has values that 'arbitrarily' go up/down at each
   * sampling. An example could be CPU load
   */
  GAUGE("gauge")
  ;

  /**
   * Convert the string representation in to an enum
   * @param in the String representation
   * @return the matching Enum
   * @throws IllegalArgumentException if in is not a valid enum value
   */
  public static MpMType from(String in) { [..] }

  [...]
}
----

==== Units

[source]
----
public enum MpMUnit {
  /** Dummy to say that this has no unit */
  NONE ("none"),

  /** A single Bit. Not defined by SI, but by IEC 60027 */
  BIT("bit"),
  /** 1000 {@link #BIT} */
  KILOBIT("kilobit"),
  /** 1000 {@link #KIBIBIT} */
  MEGABIT("megabit"),
  /** 1000 {@link #MEGABIT} */
  GIGABIT("gigabit"),
  /** 1024 {@link #BIT} */
  KIBIBIT("kibibit"),
  /** 1024 {@link #KIBIBIT}  */
  MEBIBIT("mebibit"),
  /** 1024 {@link #MEBIBIT} */
  GIBIBIT("gibibit"), /* 1024 mebibit */

  /** 8 {@link #BIT} */
  BYTE ("byte"),
  /** 1024 {@link #BYTE} */
  KILOBYTE ("kbyte"),
  /** 1024 {@link #KILO_BYTE} */
  MEGABYTE ("mbyte"),
  /** 1024 {@link #MEGA_BYTE} */
  GIGABYTE("gbyte"),

  NANOSECOND("ns"),
  MICROSECOND("us"),
  MILLISECOND("ms"),
  SECOND("s"),
  MINUTE("m"),
  HOUR("h"),
  DAY("d"),

  PERCENT("%")

  ;

  /**
   * Convert the string representation in to an enum
   * @param in the String representation
   * @return the matching Enum
   * @throws IllegalArgumentException if in is not a valid enum value
   */
  public static MpMUnit from(String in) { [..] }

  [...]
}
----

==== Application Metrics access

[source]
----
public class ApplicationMetrics implements Serializable {
  /**
   * Register an application metric via its metadata.
   * It is required that each application metric has a unique name
   * set in its metadata.
   * If a metric is registered, but no value has been set yet, it will
   * return 0 - both via REST api and via #getValue
   * @param theData The metadata
   */
  public void registerMetric(MetadataEntry theData) { }

  /**
   * Store a value for key to be exposed by the rest-api
   * @param key the name of a metric
   * @param value the value
   * @throws IllegalArgumentException if the key was not registered.
   */
  public void storeValue(String key, Number value) { }

  /**
   * Retrieve the value of the key
   * @param key The name of the metric
   * @throws IllegalArgumentException if the key was not registered.
   * @return a numeric value
   */
  public Number getValue(String key) { }

  /**
   * Increase the value of a given metric by a certain delta
   * @param key The name of the metric
   * @param increment increment (could be negative to decrement)
   * @return The new value
   * @throws IllegalArgumentException if the key was not registered.
   */
  public Number bumpValue(String key, int increment) { }

}
----

== Appendix

=== Alternatives considered

There exists Jolokia as JMX-HTTP bridge. Using this for application specific metrics requires that those metrics
are exposed to JMX first, which are many users not familiar with.

=== References

https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html[http return codes]

https://github.com/pilhuhn/rhq/blob/78eb557ae8f799b628769d76ccece61b6cb452a4/modules/core/domain/src/main/java/org/rhq/core/domain/measurement/MeasurementUnits.java#L43-79[1, RHQ Measurement Units]

https://github.com/unitsofmeasurement[UoM,JSR 363]

http://metrics20.org/spec/[Metrics2.0]

=== Example configuration format for base and vendor-specific data


The following is an example configuration in YAML format.

[source]
----
base:
  - name: "thread-count"
    mbean: "java.lang:type=Threading/ThreadCount"
    description: "Number of currently deployed threads"
    unit: "none"
    type: "gauge"
    displayName: "Current Thread count"
  - name: "peak-thread-count"
    mbean: "java.lang:type=Threading/PeakThreadCount"
    description: "Max number of threads"
    unit: "none"
    type: "gauge"
  - name: "total-started-thread-count"
    mbean: "java.lang:type=Threading/TotalStartedThreadCount"
    description: "Number of threads started for this server"
    unit: "none"
    type: "counter"
  - name: "max-heap"
    mbean: "java.lang:type=Memory/HeapMemoryUsage#max"
    description: "Number of threads started for this server"
    unit: "bytes"
    type: "counter"
    tags: "kind=memory"

vendor:
  - name: "msc-loaded-modules"
    mbean: "jboss.modules:type=ModuleLoader,name=BootModuleLoader-2/LoadedModuleCount"
    description: "Number of loaded modules"
    unit: "none"
    type: "gauge"
----

This configuration can be backed into the runtime or be provided via an external configuration file.
