//
// Copyright (c) 2016, 2023 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

[[rest-endpoints]]
== REST endpoints

This section describes the REST-API, that monitoring agents would use to retrieve the collected metrics.
(Java-) methods mentioned refer to the respective Objects in the Java API. See also <<app-programming-model#app-programming-model>>

NOTE: While vendors are required to provide a `/metrics` endpoint, as described in this section, it is permissible for implementations to be configurable to run without the endpoint in cases where the metrics capability is not wanted or a different monitoring backend is in use that does not require the endpoint.

=== Prometheus / OpenMetrics formats

The REST API must respond to GET requests with data formatted according to the Prometheus text-based exposition format, version 0.0.4 (hereafter Prometheus format). For details of how to format metrics data in this format, see https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details[Prometheus format].

Implementations may additionally provide the ability to respond to GET requests with data formatted according to the OpenMetrics exposition format, version 1.0 (hereafter OpenMetrics format).  For details on how to format metrics data in this format, see https://prometheus.io/docs/instrumenting/exposition_formats/#openmetrics-text-format[OpenMetrics format].

This section provides the details of how to map from the Gauge, Counter, Timer and Histogram types defined in this specification into appropriate fields in the Prometheus format.

Details of how to format metric names, including conventions, special character mapping and placement of the unit (if provided) in the name, are as described by the Prometheus format and OpenMetrics format documentation.

Quantile values, as used in Histogram and Timer output, should represent recent values (typically from the last 5-10 minutes).  If no data is available from that timeframe, the value must be set to NaN.


==== Gauge

.Example Gauge with unit `celsius` in Prometheus format.
[source, ruby]
----
# HELP current_temperature_celsius The current temperature. <1>
# TYPE current_temperature_celsius gauge <2>
current_temperature_celsius{mp_scope="application",server="front_office"} 36.2 <3>
----

<1> The description of the gauge, from the `getDescription()` method of the `Metadata` associated to the gauge, must be provided in the HELP line

<2> The type of the metric, in this case `gauge`, must be shown in the TYPE line

<3> The value specified must be the value of the gauge's `getValue()` method. Tags, if provided, are included in brackets separated by commas.


==== Counter

.Example Counter with unit `events` in Prometheus format.
[source, ruby]
----
# HELP messages_processed_events_total Number of messages handled <1>
# TYPE messages_processed_events_total counter <2>
messages_processed_events_total{mp_scope="application"} 1.0 <3>
----

<1> The description of the counter must be provided in the HELP line

<2> The type of the metric, in this case `counter`, must be shown in the TYPE line

<3> The value specified must be the value of the counter's `getCount()` method. Tags, if provided, are included in brackets separated by commas. By convention, `_total` should be added to the end of the counter name.


==== Histogram

.Example Histogram with unit `meters` in Prometheus format.
[source, ruby]
----
# HELP distance_to_hole_meters_max Distance of golf ball to hole <1>
# TYPE distance_to_hole_meters_max gauge <2>
distance_to_hole_meters_max{mp_scope="golf_stats"} 12.722726616315509 <3>
# HELP distance_to_hole_meters Distance of golf ball to hole <1>
# TYPE distance_to_hole_meters summary <2>
distance_to_hole_meters{mp_scope="golf_stats",quantile="0.5"} 2.8748779296875 <3>
distance_to_hole_meters{mp_scope="golf_stats",quantile="0.75"} 4.4998779296875 <3>
distance_to_hole_meters{mp_scope="golf_stats",quantile="0.95"} 7.9998779296875 <3>
distance_to_hole_meters{mp_scope="golf_stats",quantile="0.98"} 9.4998779296875 <3>
distance_to_hole_meters{mp_scope="golf_stats",quantile="0.99"} 11.9998779296875 <3>
distance_to_hole_meters{mp_scope="golf_stats",quantile="0.999"} 12.9998779296875 <3>
distance_to_hole_meters_count{mp_scope="golf_stats"} 487.0 <3>
distance_to_hole_meters_sum{mp_scope="golf_stats"} 1569.3785694223322 <3>
----

`Histogram` output is comprised of a maximum section and a summary section.

<1> The description of the histogram must be provided on the HELP lines for the maximum and summary

<2> The type of the metrics, in this case `gauge` (for the maximum) and `summary` for the summary. The `summary` type is comprised of the count, sum and multiple quantile values.

<3> The value of each metric included in the output is described in the table below. Tags, if provided, are included in brackets separated by commas. Percentile metrics include a `quantile` label that is merged with the metric's tags.


.Prometheus format mapping for a Histogram metric
[cols="6,4,8,3"]
|===
| Suffix{label}                   | TYPE    | Value (Histogram method)                 | Units

| `<units>_max`                   | Gauge   | `getSnapshot().getMax()`                 | <units>
| `<units>{quantile="0.5"}`       | Summary | `getSnapshot().percentileValues()` ^1^   | <units>
| `<units>{quantile="0.75"}`      | Summary | `getSnapshot().percentileValues()` ^1^   | <units>
| `<units>{quantile="0.95"}`      | Summary | `getSnapshot().percentileValues()` ^1^   | <units>
| `<units>{quantile="0.98"}`      | Summary | `getSnapshot().percentileValues()` ^1^   | <units>
| `<units>{quantile="0.99"}`      | Summary | `getSnapshot().percentileValues()` ^1^   | <units>
| `<units>{quantile="0.999"}`     | Summary | `getSnapshot().percentileValues()` ^1^   | <units>
| `<units>_count`                 | Summary | `getCount()`                             | <units>
| `<units>_sum`                   | Summary | `getSum()`                               | <units>
|===

^1^ This will return an array of `PercentileValue` objects that will need to be iterated through to find the specific percentile and its value

==== Timer

.Example Timer in Prometheus format.  Timers use `seconds` as the unit.
[source, ruby]
----
# HELP myClass_myMethod_seconds duration of myMethod <1>
# TYPE myClass_myMethod_seconds summary <2>
myClass_myMethod_seconds{mp_scope="vendor",quantile="0.5"} 0.0524288 <3>
myClass_myMethod_seconds{mp_scope="vendor",quantile="0.75"} 0.0524288 <3>
myClass_myMethod_seconds{mp_scope="vendor",quantile="0.95"} 0.054525952 <3>
myClass_myMethod_seconds{mp_scope="vendor",quantile="0.98"} 0.054525952 <3>
myClass_myMethod_seconds{mp_scope="vendor",quantile="0.99"} 0.054525952 <3>
myClass_myMethod_seconds{mp_scope="vendor",quantile="0.999"} 0.054525952 <3>
myClass_myMethod_seconds_count{mp_scope="vendor"} 100.0 <3>
myClass_myMethod_seconds_sum{mp_scope="vendor"} 5.310349419 <3>
# HELP myClass_myMethod_seconds_max duration of myMethod <1>
# TYPE myClass_myMethod_seconds_max gauge <2>
myClass_myMethod_seconds_max{mp_scope="vendor"} 0.05507899 <3>
----

`Timer` output is comprised of a maximum section and a summary section.

<1> The description of the timer must be provided on the HELP lines for the maximum and summary

<2> The type of the metrics, in this case `gauge` (for the maximum) and `summary` for the summary. The `summary` type is comprised of the count, sum and multiple quantile values.

<3> The value of each metric included in the output is described in the table below. Tags, if provided, are included in brackets separated by commas. Percentile metrics include a `quantile` label that is merged with the metric's tags.


.Prometheus format mapping for a Timer metric
[cols="6,4,8,3"]
|===
| Suffix{label}                   | TYPE    | Value (Timer method)                   | Units

| `max_seconds`                   | Gauge   | `getSnapshot().getMax()`               | SECONDS^1^
| `seconds{quantile="0.5"}`       | Summary | `getSnapshot().percentileValues()` ^2^ | SECONDS^1^
| `seconds{quantile="0.75"}`      | Summary | `getSnapshot().percentileValues()` ^2^ | SECONDS^1^
| `seconds{quantile="0.95"}`      | Summary | `getSnapshot().percentileValues()` ^2^ | SECONDS^1^
| `seconds{quantile="0.98"}`      | Summary | `getSnapshot().percentileValues()` ^2^ | SECONDS^1^
| `seconds{quantile="0.99"}`      | Summary | `getSnapshot().percentileValues()` ^2^ | SECONDS^1^
| `seconds{quantile="0.999"}`     | Summary | `getSnapshot().percentileValues()` ^2^ | SECONDS^1^
| `seconds_count`                 | Summary | `getCount()`                           | SECONDS^1^
| `seconds_sum`                   | Summary | `getElapsedTime()`                     | SECONDS^1^
|===

^1^ The implementation is expected to convert the result returned by the `Timer` into seconds

^2^ This will return an array of `PercentileValue` objects that will need to be iterated through to find the specific percentile and its value

=== Additional output and customization for histograms and timers

This section defines MicroProfile Config properties that extend the output of histogram and timers. This includes customizing the percentile output as well as enabling and customizing histogram-bucket values. These MicroProfile config properties are defined at the server level.

[[percentile-configuration]]
==== Percentile customization for histogram and timers

The percentiles that are tracked and are output can be overridden and customized by using the MicroProfile Config property `mp.metrics.distribution.percentiles`. The property follows these rules:

* The property accepts a semi-colon separated set of values that consists of a metric name followed by an equals sign (`=`) and comma separated percentile values _(See <<percentiles-examples,examples>> below)_.
* The asterisk (`*`) can be used as a wildcard at the end of the metric name.
* The percentile values are decimal values between 0.0 and 1.0 inclusively. 
* Setting the property with a metric name but no percentile values disables percentile output for that metric.
* Setting the property without any value disables percentiles for all histogram and timer metrics.
* Values defined later take precedence over values before (i.e., right to left precedence).

[[percentiles-examples]]
.MicroProfile Config `mp.metrics.distribution.percentiles` property examples
----
//alpha.histogram will publish the 30th and 40th percentile and alpha.timer will publish the 50th and 80th percentile
mp.metrics.distribution.percentiles=alpha.histogram=0.3,0.4;alpha.timer=0.5,0.8

//any timer or histogram that match alpha.* will publish the 60th percentile
mp.metrics.distribution.percentiles=alpha.*=0.6

//any timer or histogram that match alpha.* will publish the 60th percentile and alpha.test.histogram which will only publish the 40th percentile due to precedence
mp.metrics.distribution.percentiles=alpha.*=0.6;alpha.test.histogram=0.4

//disables percentiles for all histogram and timer metrics
mp.metrics.distribution.percentiles=*=

//disables percentiles for all histogram and timer metrics
mp.metrics.distribution.percentiles=
----

NOTE: Histograms and Timers that do not match the metric name definitions of the `mp.metrics.distribution.percentiles` property will output the default 50th, 75th, 95th, 99th and 99.9th percentiles.

==== Defining histogram-buckets for histograms and timers

The MicroProfile Metrics runtime offers MicroProfile Config properties to enable and explicitly set (cumulative) histogram-buckets for histograms and timers.
The property `mp.metrics.distribution.timer.slo` applies to timer metrics and the property `mp.metrics.distribution.histogram.buckets` applies to histograms. These two properties follow these rules unless explicitly describing a specific property:

* The property accepts a semi-colon separated set of values that consists of a metric name followed by an equals sign (`=`) and comma separated bucket values:
** `mp.metrics.distribution.histogram.buckets` accepts a comma separated list of decimal and integer values greater than 0 _(See <<histogram-bucket-sample,examples>> below)_.
** `mp.metrics.distribution.timer.slo` accepts a comma separated list of integers with an appended time unit (valid time units are `ms` for milliseconds, `s` for seconds, `m` for minutes and `h` for hours). Decimal values will not be accepted. Values with no time unit default to seconds. _(See <<timer-slo-sample,examples>> below)_
* The asterisk (`*`) can be used as a wildcard at the end of the metric name.
* Defining a metric name with no bucket values provides no effect.
* Values defined later take precedence over values before (i.e., right to left precedence).

NOTE: When customizing histogram-bucket values for the histogram and timer metrics, the metrics included in the Prometheus output will automatically switch from a `summary` type to the `histogram` type. Any percentile values that are also outputted will belong under the `histogram` type. The Prometheus output will also automatically include a `+Inf` bucket to capture all values. This will be demonstrated in the <<histogram-bucket-output, histogram sample output>> and <<timer-slo-output, timer sample output>>. The metric output for the buckets will also be appended with `_bucket`, and a tag `le` is used to denote the bucket value.

[[histogram-bucket-sample]]
.MicroProfile Config `mp.metrics.distribution.histogram.buckets` property examples
----
//alpha.histogram will publish histogram-buckets with maximum values of 10.0, 50.0 and 100.0 while the beta.histogram will publish histogram buckets with maximum values of 30.0, 50 and 123.
mp.metrics.distribution.histogram.buckets=alpha.histogram=10.0,50.0,100.0;beta.histogram=30.0,50.0,123

//any histogram that matches with `beta.*` will publish histograms buckets with maximum values of 50.0 and 100.0 except the beta.test.histogram which will publish a bucket with a maximum value of 100.0 due to precedence.
mp.metrics.distribution.histogram.buckets=beta.*=50.0,100.0;beta.test.histogram=100.0

----

NOTE: Histograms that do not match the metric name definitions of the `mp.metrics.distribution.histogram.buckets` property will output no buckets.

The following is a sample output of the `alpha.histogram` defined in the first `mp.metrics.distribution.histogram.buckets` definition above.

[[histogram-bucket-output]]
.Sample alpha.histogram Prometheus output
----
# HELP alpha_histogram_cookies  
# TYPE alpha_histogram_cookies histogram <1>
alpha_histogram_cookies{mp_scope="application",quantile="0.5",} 9.25 <2>
alpha_histogram_cookies{mp_scope="application",quantile="0.75",} 51.75 <2>
alpha_histogram_cookies{mp_scope="application",quantile="0.95",} 51.75 <2>
alpha_histogram_cookies{mp_scope="application",quantile="0.98",} 51.75 <2>
alpha_histogram_cookies{mp_scope="application",quantile="0.99",} 51.75 <2>
alpha_histogram_cookies{mp_scope="application",quantile="0.999",} 51.75 <2>
alpha_histogram_cookies_bucket{mp_scope="application",le="10.0",} 2.0 <3>
alpha_histogram_cookies_bucket{mp_scope="application",le="50.0",} 3.0 <3>
alpha_histogram_cookies_bucket{mp_scope="application",le="100.0",} 3.0 <3>
alpha_histogram_cookies_bucket{mp_scope="application",le="+Inf",} 3.0 <3><4>
alpha_histogram_cookies_count{mp_scope="application",} 3.0
alpha_histogram_cookies_sum{mp_scope="application",} 64.0
# HELP alpha_histogram_cookies_max  
# TYPE alpha_histogram_cookies_max gauge
alpha_histogram_cookies_max{mp_scope="application",} 50.0
----
<1> The Prometheus metric type is `histogram`

<2> percentiles are part of  the `histogram` type instead of `summary`

<3> histogram buckets

<4> The `+Inf` bucket is included in the output



[[timer-slo-sample]]
.MicroProfile Config `mp.metrics.distribution.timer.slo` property examples
----
//alpha.timer will publish histogram-buckets with maximum values of 500 milliseconds, 2 seconds, and 3 minutes while the beta.histogram will publish histogram buckets with maximum values of 10 seconds, 2 minutes and 5 hours. Timer metrics that do not match will not have any histogram buckets.
mp.metrics.distribution.timer.slo=alpha.timer=10,500ms,2s,3m;beta.timer=10s,2m,5h

//any histogram that matches with `alpha.*` will publish histograms buckets with maximum values of 50 seconds and 100 seconds the alpha.test.histogram which will publish a bucket with a maximum value 100.0 due to precedence. Timer metrics that do not match will not have any histogram buckets.
mp.metrics.distribution.timer.slo=alpha.*=50s, 100s;alpha.test.timer=100.0

----

NOTE: Timers that do not match the metric name definitions of the `mp.metrics.distribution.timer.slo` property will output no buckets.

NOTE: The time units defined by the property will be converted to second based buckets for the Prometheus output as timers are based in seconds.

The following is a sample output of the `alpha.timer` defined in the first `mp.metrics.distribution.timer.slo` definition above.

[[timer-slo-output]]
.Sample alpha.timer Prometheus output
----
# HELP alpha_timer_seconds_max  
# TYPE alpha_timer_seconds_max gauge
alpha_timer_seconds_max{mp_scope="application"} 5.633
# HELP alpha_timer_seconds  
# TYPE alpha_timer_seconds histogram <1>
alpha_timer_seconds{mp_scope="application", quantile="0.5",} 0.67108864 <2>
alpha_timer_seconds{quantile="0.75",} 5.603590144 <2>
alpha_timer_seconds{mp_scope="application", quantile="0.95",} 5.603590144 <2>
alpha_timer_seconds{mp_scope="application", quantile="0.98",} 5.603590144 <2>
alpha_timer_seconds{mp_scope="application", quantile="0.99",} 5.603590144 <2>
alpha_timer_seconds{mp_scope="application", quantile="0.999",} 5.603590144 <2>
alpha_timer_seconds_bucket{mp_scope="application", le="0.5",} 0.0 <3><5>
alpha_timer_seconds_bucket{mp_scope="application", le="2.0",} 1.0 <3><5>
alpha_timer_seconds_bucket{mp_scope="application", le="180.0",} 2.0 <3><5>
alpha_timer_seconds_bucket{mp_scope="application", le="+Inf",} 2.0 <3><4>
alpha_timer_seconds_count{mp_scope="application"} 2.0
alpha_timer_seconds_sum{mp_scope="application"} 6.333
----

<1> The Prometheus metric type is `histogram`

<2> percentiles are part of  the `histogram` type instead of `summary`

<3> histogram buckets

<4> The `+Inf` bucket is included in the output

<5> bucket values converted to seconds

==== (Optional) Enabling a default set of histogram-buckets for histogram and timers

Vendors may choose to optionally provide the `mp.metrics.distribution.percentiles-histogram.enabled` property. This will enable a matching histogram or timer metrics to output a default set of bucket values defined by the vendor. The property follows these rules:

* The property accepts a semi-colon separated set of values that consists of a metric name followed by an equals sign (`=`) and either `true` or `false` (see <<default-buckets-sample,example>> below).
* The asterisk (`*`) can be used as a wildcard at the end of the metric name.
* Defining a metric name with no values or invalid values has no effect.
* Values defined later take precedence over values before (i.e., right to left precedence).

[[default-buckets-sample]]
.MicroProfile Config `mp.metrics.distribution.percentiles-histogram.enabled` property examples
----
//vendor will provide default buckets for the alpha.timer 
mp.metrics.distribution.percentiles-histogram.enabled=alpha.timer=true;alpha.histogram=false
----

NOTE: The `mp.metrics.distribution.percentiles-histogram.enabled` property does not affect any buckets defined by the `mp.metrics.distribution.histogram.buckets` or `mp.metrics.distribution.timer.slo` properties. A `false` value for `mp.metrics.distribution.percentiles-histogram.enabled` will not disable any custom buckets defined by `mp.metrics.distribution.histogram.buckets` or `mp.metrics.distribution.timer.slo` for any matching histogram or timer.

It is recommended that if the vendor provides support for the `mp.metrics.distribution.percentiles-histogram.enabled` property, then the following properties be supported as well:

* `mp.metrics.distribution.histogram.minimum-expected-value`
* `mp.metrics.distribution.histogram.maximum-expected-value`
* `mp.metrics.distribution.timer.minimum-expected-value` 
* `mp.metrics.distribution.timer.maximum-expected-value`

The number of default buckets and maximum value of each of those default buckets may vary between vendor implementations. These properties are used to set a minimum and maximum limit for the default buckets provided when `mp.metrics.distribution.percentiles-histogram.enabled` has enabled default buckets for the matching metric. The properties share the following rules and explicit rules are outlined for specific properties:

* The property accepts a semi-colon separated set of values that define a metric name followed by an equals sign (`=`) and a value:
** `mp.metrics.distribution.histogram.*` properties accepts a decimal or integer values greater than 0 _(See <<min-max-sample,examples>> below)_.
** `mp.metrics.distribution.timer.*` accepts an integer value with an appended time unit (valid time units are `ms` for milliseconds, `s` for seconds, `m` for minutes and `h` for hours). Decimal values will not be accepted. Values with no time unit will default to seconds. _(See <<min-max-sample,examples>> below)_
* The asterisk (`*`) can be used as a wildcard at the end of the metric name.
* Defining a metric name with no value provides no effect.
* Values defined later take precedence over values before (i.e., right to left precedence).




[[min-max-sample]]
.MicroProfile Config histogram/timer min/max property examples
----
//any histogram matching alpha.* will not have any buckets in the output that are below 300 except alpha.histogram which has a lower bound of 400 due to precedence
mp.metrics.distribution.histogram.minimum-expected-value=alpha.*=300;alpha.histogram=400

//any histogram matching alpha.* will not have any buckets in the output that are above 500 except alpha.histogram which has a upper bound of 400 due to precedence
mp.metrics.distribution.histogram.maximum-expected-value=alpha.*=500;alpha.histogram=400

//any timer matching alpha.* will not have any buckets in the output that are above 1 second except alpha.histogram which has a upper bound of 0.5 seconds due to precedence
mp.metrics.distribution.timer.maximum-expected-value=alpha.*=1s;alpha.timer=500ms

//any timer matching alpha.* will not have any buckets in the output that are below 0.4 second except alpha.histogram which has a lower bound of 0.5 seconds due to precedence
mp.metrics.distribution.timer.minimum-expected-value=alpha.*=400ms;alpha.timer=500ms
----

NOTE: The use of the min and max properties do not apply to the buckets defined through `mp.metrics.distribution.timer.slo` and `mp.metrics.distribution.histogram.buckets` properties.

=== Security

It must be possible to secure the endpoints via the usual means. The definition of 'usual means' is in
this version of the specification implementation specific.

In case of a secured endpoint, accessing `/metrics` without valid credentials must return a `401 Unauthorized` header.

A server SHOULD implement TLS encryption by default.

It is allowed to ignore security for trusted origins (e.g. localhost)
