//
// Copyright (c) 2016-2018 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

[[rest_endpoints]]
== REST endpoints

This section describes the REST-api, that monitoring agents would use to retrieve the collected metrics.
(Java-) methods mentioned refer to the respective Objects in the Java API. See also <<app-metrics-api>>

[[json-format-def]]
=== JSON format

* When using JSON format, the REST API will respond to GET requests with data formatted in a tree like fashion with sub-trees for the sub-resources.
A sub-tree that does not contain data must be omitted.
* A 'shadow tree' that responds to OPTIONS will provide the metadata and tags associated to a metric name.

==== Translation rules for metric names and handling of tags

The following rules apply only to GET requests:

* Tags are appended to the leaf element of the metric's JSON tree.
* For metrics with tags, the metric name must be appended with a semicolon `;` followed by a semicolon-separated list of tag key/value pairs.
* For compound metrics (those with child JSON attributes) with tags, only the "leaf" metric names are decorated with tags.
* Semicolons `;` present in tag values must be converted to underscores `_` in JSON output.

For example:
[source, json]
----
{
 "carsCounter;colour=red" : 0,
 "carsCounter;colour=blue;car=sedan" : 0,
 "carsMeter": {
    "count;colour=red" : 0,
    "meanRate;colour=red" : 0,
    "oneMinRate;colour=red" : 0,
    "fiveMinRate;colour=red" : 0,
    "fifteenMinRate;colour=red" : 0,
    "count;colour=blue" : 0,
    "meanRate;colour=blue" : 0,
    "oneMinRate;colour=blue" : 0,
    "fiveMinRate;colour=blue" : 0,
    "fifteenMinRate;colour=blue" : 0
 }
}
----

The following apply to both GET and OPTION requests:

* Each tag is a key-value-pair in the format of `<key>=<value>`. The list of tags must be sorted alphabetically by key name.
* If the metric name or tag value contains a special reserved JSON character, these characters must be escaped in the JSON response.


If the metric has no tags, the semicolon `;` must be omitted.

For example,
[source, json]
----
{
  "metricWithoutTags": 192
}
----


*REST-API Objects*

API-objects MAY include one or more metrics as in

[source, json]
----
{
  "thread.count" : 33,
  "thread.max.count" : 47,
  "memory.maxHeap" : 3817863211,
  "memory.usedHeap" : 16859081,
  "memory.committedHeap" : 64703546
}
----

or

[source, json]
----
{
  "hitCount;type=yes": 45
}
----

In case `/metrics` is requested, then the data for the scopes are wrapped in the scope name:

[source, json]
----
{
  "application": {
    "hitCount": 45
  },
  "base": {
     "thread.count" : 33,
     "thread.max.count" : 47
  },
  "vendor": {...}
}
----

==== Gauge JSON Format

The value of the gauge must be equivalent to a call to the instance Gauge's `getValue()`.

.Example Gauge JSON GET Response
[source, json]
----
{
  "responsePercentage": 48.45632,
  "responsePercentage;servlet=two": 26.23654,
  "responsePercentage;store=webshop;servlet=three": 29.24554
}
----

==== Counter JSON Format

The value of the counter must be equivalent to a call to the instance Counter's `getCount()`.

.Example Counter JSON GET Response
[source, json]
----
{
  "hitCount": 45,
  "hitCount;servlet=two": 3,
  "hitCount;store=webshop;servlet=three": 4
}
----

==== Concurrent Gauge JSON Format

`ConcurrentGauge` is a complex metric type comprised of multiple key/values. The format is specified by the table below.

.JSON mapping for a ConcurrentGauge metric
[cols="1,4"]
|===
| JSON Key | Value (Equivalent ConcurrentGauge method)

| `current` | `getValue()`
| `min` | `getMin()`
| `max` | `getMax()`
|===

.Example ConcurrentGauge JSON GET Response
[source, json]
----
{
  "callCount": {
      "current" : 48,
      "min": 4,
      "max": 50,
      "current;component=backend" : 23,
      "min;component=backend": 1,
      "max;component=backend": 29
  }
}
----


==== Meter JSON Format

`Meter` is a complex metric type comprised of multiple key/values. The format is specified by the table below.

.JSON mapping for a Meter metric
[cols="1,4"]
|===
| JSON Key | Value (Equivalent Meter method)

| `count` | `getCount()`
| `meanRate` | `getMeanRate()`
| `oneMinRate` | `getOneMinuteRate()`
| `fiveMinRate` | `getFiveMinuteRate()`
| `fifteenMinRate` | `getFifteenMinuteRate()`
|===

.Example Meter JSON GET Response
[source, json]
----
{
  "requests": {
    "count": 29382,
    "meanRate": 12.223,
    "oneMinRate": 12.563,
    "fiveMinRate": 12.364,
    "fifteenMinRate": 12.126,
    "count;servlet=one": 29382,
    "meanRate;servlet=one": 12.223,
    "oneMinRate;servlet=one": 12.563,
    "fiveMinRate;servlet=one": 12.364,
    "fifteenMinRate;servlet=one": 12.126,
    "count;servlet=two": 29382,
    "meanRate;servlet=two": 12.223,
    "oneMinRate;servlet=two": 12.563,
    "fiveMinRate;servlet=two": 12.364,
    "fifteenMinRate;servlet=two": 12.126
  }
}
----


==== Histogram JSON Format

`Histogram` is a complex metric type comprised of multiple key/values. The format is specified by the table below.

.JSON mapping for a Histogram metric
[cols="1,4"]
|===
| JSON Key | Value (Equivalent Histogram method)

| `count` | `getCount()`
| `min` | `getSnapshot().getMin()`
| `max` | `getSnapshot().getMax()`
| `mean` | `getSnapshot().getMean()`
| `stddev` | `getSnapshot().getStdDev()`
| `p50` | `getSnapshot().getMedian()`
| `p75` | `getSnapshot().get75thPercentile()`
| `p95` | `getSnapshot().get95thPercentile()`
| `p98` | `getSnapshot().get98thPercentile()`
| `p99` | `getSnapshot().get99thPercentile()`
| `p999` | `getSnapshot().get999thPercentile()`
|===

.Example Histogram JSON GET Response
[source, json]
----
{
  "daily_value_changes": {
    "count":2,
    "min":-1624,
    "max":26,
    "mean":-799.0,
    "stddev":825.0,
    "p50":26.0,
    "p75":26.0,
    "p95":26.0,
    "p98":26.0,
    "p99":26.0,
    "p999":26.0,
    "count;servlet=two":2,
    "min;servlet=two":-1624,
    "max;servlet=two":26,
    "mean;servlet=two":-799.0,
    "stddev;servlet=two":825.0,
    "p50;servlet=two":26.0,
    "p75;servlet=two":26.0,
    "p95;servlet=two":26.0,
    "p98;servlet=two":26.0,
    "p99;servlet=two":26.0,
    "p999;servlet=two":26.0
  }
}
----


==== Timer JSON Format

`Timer` is a complex metric type comprised of multiple key/values. The format is specified by the table below.

.JSON mapping for a Timer metric
[cols="1,4"]
|===
| JSON Key | Value (Equivalent Timer method)

| `count` | `getCount()`
| `meanRate` | `getMeanRate()`
| `oneMinRate` | `getOneMinuteRate()`
| `fiveMinRate` | `getFiveMinuteRate()`
| `fifteenMinRate` | `getFifteenMinuteRate()`
| `min` | `getSnapshot().getMin()`
| `max` | `getSnapshot().getMax()`
| `mean` | `getSnapshot().getMean()`
| `stddev` | `getSnapshot().getStdDev()`
| `p50` | `getSnapshot().getMedian()`
| `p75` | `getSnapshot().get75thPercentile()`
| `p95` | `getSnapshot().get95thPercentile()`
| `p98` | `getSnapshot().get98thPercentile()`
| `p99` | `getSnapshot().get99thPercentile()`
| `p999` | `getSnapshot().get999thPercentile()`
|===

.Example Timer JSON GET Response
[source, json]
----
{
  "responseTime": {
    "count": 29382,
    "meanRate":12.185627192860734,
    "oneMinRate": 12.563,
    "fiveMinRate": 12.364,
    "fifteenMinRate": 12.126,
    "min":169916,
    "max":5608694,
    "mean":415041.00024926325,
    "stddev":652907.9633011606,
    "p50":293324.0,
    "p75":344914.0,
    "p95":543647.0,
    "p98":2706543.0,
    "p99":5608694.0,
    "p999":5608694.0,
    "count;servlet=two": 29382,
    "meanRate;servlet=two":12.185627192860734,
    "oneMinRate;servlet=two": 12.563,
    "fiveMinRate;servlet=two": 12.364,
    "fifteenMinRate;servlet=two": 12.126,
    "min;servlet=two":169916,
    "max;servlet=two":5608694,
    "mean;servlet=two":415041.00024926325,
    "stddev;servlet=two":652907.9633011606,
    "p50;servlet=two":293324.0,
    "p75;servlet=two":344914.0,
    "p95;servlet=two":543647.0,
    "p98;servlet=two":2706543.0,
    "p99;servlet=two":5608694.0,
    "p999;servlet=two":5608694.0
  }
}
----

==== Metadata


Metadata is exposed in a tree-like fashion with sub-trees for the sub-resources mentioned previously.
Tags from metrics associated with the metric name are also included. The 'tags' attribute is an array of nested arrays which hold tags from different metrics that are associated with the metadata.

Example:

If `GET /metrics/base/fooVal` exposes:

[source]
----
{
  "fooVal;store=webshop": 12345
}
----

then `OPTIONS /metrics/base/fooVal` will expose:

[source]
----

{
  "fooVal": {
    "unit": "milliseconds",
    "type": "gauge",
    "description": "The size of foo after each request",
    "displayName": "Size of foo",
    "tags": [
      [
        "store=webshop"
      ]
    ]
  }
}

----

If `GET /metrics/base` exposes multiple values like this:

.Example of exposed metrics data
[source]
----
{
  "fooVal;store=webshop": 12345,
  "barVal;store=webshop;component=backend": 42,
  "barVal;store=webshop;component=frontend": 63
}
----

then `OPTIONS /metrics/base` exposes:

.Example of JSON output of Metadata
[source]
----
{
  "fooVal": {
    "unit": "milliseconds",
    "type": "gauge",
    "description": "The average duration of foo requests during last 5 minutes",
    "displayName": "Duration of foo",
    "tags": [
      [
        "store=webshop"
      ]
    ]
  },
  "barVal": {
    "unit": "megabytes",
    "type": "gauge",
    "tags": [
      [
        "store=webshop",
        "component=backend"
      ],
      [
        "store=webshop",
        "component=frontend"
      ]
    ]
  }
}
----


=== OpenMetrics format

Data is exposed in the OpenMetrics text format, version 0.0.4 as described in
https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details[OpenMetrics text format].

The metadata will be included as part of the normal OpenMetrics text format. Unlike the JSON format, the text format does not support OPTIONS requests.

TIP: Users that want to write tools to transform the metadata can still request the metadata via OPTIONS
request and `application/json` media type.

The above json example would look like this in OpenMetrics format

.Example of OpenMetrics output
[source]
----
# TYPE base_fooVal_seconds gauge
# HELP base_fooVal_seconds The average duration of foo requests during last 5 minutes <1>
base_fooVal_seconds{store="webshop"} 12.345  <2>
# TYPE base_barVal_bytes gauge
base_barVal_bytes{component="backend", store="webshop"} 42000 <2>
# TYPE base_barVal_bytes gauge
base_barVal_bytes{component="frontend", store="webshop"} 63000 <2>
----
<1> The description goes into the HELP line
<2> Metric names gets the base unit of the family appended with `_` and defined labels. Values are scaled accordingly. See <<OpenMetrics_units>>

==== Translation rules for metric names

OpenMetrics text format does not allow for all characters and adds the base unit of a family to the name.
Characters allowed are `[a-zA-Z0-9_]` (Ascii alphabet, numbers and underscore). Exposed metric names must
follow the pattern `[a-zA-Z_][a-zA-Z0-9_]*`.

* Characters that do not fall in above category are translated to underscore (`_`).
* Scope is always specified at the start of the metric name.
* Scope and name are separated by underscore (`_`).
* Double underscore is translated to single underscore
* The unit is appended to the name, separated by underscore. See <<OpenMetrics_units>>


==== Handling of tags

Metric tags are appended to the metric name in curly braces `{` and `}` and are separated by comma.
Each tag is a key-value-pair in the format of `<key>="<value>"` (the quotes around the value are required).

MicroProfile Metrics timers and histograms expose an OpenMetrics `summary` type which requires an additional `quantile` tag for certain metrics.
The `quantile` tag must be included alongside the metrics tags within the curly braces `{` and `}`.

The tag value can be any Unicode character but the following characters must be escaped:

* Backslash (`\`) must be escaped as `\\` (as two characters: `\` and `\`)
* Double-quotes (`"`) must be escaped as `\"` (as two characters: `\` and `"`)
* Line feed (`\n`) must be escaped as `\n` (as two characters: `\` and `n`)

[[OpenMetrics_units]]
==== Handling of units

The OpenMetrics text format adheres to using "base units" when creating the HTTP response. Due to the different context of each metric type, certain metrics' values must be converted to the respective "base unit" when responding to OpenMetrics requests. For example, times in milliseconds must be divided by 1000 and displayed in the base unit (seconds).

The following sections outline how each metric type is handled:

*Gauges and Histograms*

The metric name and values for `Gauge` and `Histogram` are converted to the "base unit" in respect to the `unit` value in the Metadata.

- If the Metadata is empty, `NONE`, or null, the metric name is used as is without appending the unit name and no scaling is applied.
- If the metric's metadata contains a known unit, as defined in the `MetricUnits` class, the OpenMetrics value should be scaled to the _base unit_ of the respective family. The name of the base unit is appended to the metric name delimited by underscores (`_`).
- If the `unit` is specified and is not defined in the `MetricUnits` class, the value is not scaled but the `unit` is still appended to the metric name delimited by underscores (`_`).


Unit families and their base units are described under https://prometheus.io/docs/practices/naming/#base-units[OpenMetrics metric names, Base units].

Families and OpenMetrics base units are:

|===
| Family | Base unit

| Bits    | bytes
| Bytes   | bytes
| Time   | seconds
| Percent | ratio (normally ratio is A_per_B, but there are exceptions like `disk_usage_ratio`)
|===

*Counters*

`Counter` metrics are considered dimensionless. The implementation must not append the unit name to the metric name and must not scale the value.


*Meters and Timers*

`Meter` and `Timer` have fixed units as described below regardless of the `unit` value in the Metadata.

==== Gauge OpenMetrics Text Format

The value of the gauge must be the value of `getValue()` with appropriate naming/scaling based on  <<OpenMetrics_units>>

.Example OpenMetrics text format for a Gauge in dollars.
[source, ruby]
----
# TYPE application_cost_dollars gauge
# HELP application_cost_dollars The running cost of the server in dollars.
application_cost_dollars 80
----

==== Counter OpenMetrics Text Format

The value of the counter must be the value of `getCount()`.
The exposed metric name must have a  `_total` suffix.
The suffix is not appended if the (translated) original metric name already ends in `_total`.
Counters do not have a suffix for the unit.

.Example OpenMetrics text format for a Counter.
[source, ruby]
----
# TYPE application_visitors_total counter
# HELP application_visitors_total The number of unique visitors
application_visitors_total 80
----

==== Concurrent Gauge OpenMetrics Text Format

`ConcurrentGauge` is a complex metric type comprised of multiple key/values. Each key will require a suffix to be appended to the metric name. The format is specified by the table below.

.OpenMetrics text mapping for a ConcurrentGauge metric
[cols="2,1,2,1"]
|===
| Suffix{label}   | TYPE    | Value (Meter method)     | Units

| `current`       | Gauge   | `getCount()`             | N/A
| `min`           | Gauge   | `getMin()`               | N/A
| `max`           | Gauge   | `getMax()`               | N/A
|===

Concurrent gauges do not have a suffix for the unit.

.Example OpenMetrics text format for a Concurrent Gauge
[source, ruby]
----
# TYPE application_method_a_invocations_current gauge
# HELP application_method_a_invocations_current The number of parallel invocations of methodA() #<1>
application_method_a_invocations_current 80
# TYPE application_method_a_invocations_min gauge
application_method_a_invocations_min 20
# TYPE application_method_a_invocations_max gauge
application_method_a_invocations_max 100
----
<1> Note help is only emitted for the metric related to `getCount()`, but not for _min and _max.

==== Meter OpenMetrics Text Format

`Meter` is a complex metric type comprised of multiple key/values. Each key will require a suffix to be appended to the metric name. The format is specified by the table below.

The `# HELP` description line is only required for the `total` value as shown below.

.OpenMetrics text mapping for a Meter metric
[cols="2,1,2,1"]
|===
| Suffix{label}                   | TYPE    | Value (Meter method)                | Units

| `total`                         | Counter | `getCount()`                        | N/A
| `rate_per_second`               | Gauge   | `getMeanRate()`                     | PER_SECOND
| `one_min_rate_per_second`       | Gauge   | `getOneMinuteRate()`                | PER_SECOND
| `five_min_rate_per_second`      | Gauge   | `getFiveMinuteRate()`               | PER_SECOND
| `fifteen_min_rate_per_second`   | Gauge   | `getFifteenMinuteRate()`            | PER_SECOND
|===

.Example OpenMetrics text format for a Meter
[source, ruby]
----
# TYPE application_requests_total counter
# HELP application_requests_total Tracks the number of requests to the server
application_requests_total 29382
# TYPE application_requests_rate_per_second gauge
application_requests_rate_per_second 12.223
# TYPE application_requests_one_min_rate_per_second gauge
application_requests_one_min_rate_per_second 12.563
# TYPE application_requests_five_min_rate_per_second gauge
application_requests_five_min_rate_per_second 12.364
# TYPE application_requests_fifteen_min_rate_per_second gauge
application_requests_fifteen_min_rate_per_second 12.126
----


==== Histogram OpenMetrics Text Format

`Histogram` is a complex metric type comprised of multiple key/values. Each key will require a suffix to be appended to the metric name with appropriate naming/scaling based on <<OpenMetrics_units>>.  The format is specified by the table below.

The `# HELP` description line is only required for the `summary` value as shown below.

.OpenMetrics text mapping for a Histogram metric
[cols="2,1,2,1"]
|===
| Suffix{label}                   | TYPE    | Value (Histogram method)            | Units

| `min_<units>`                   | Gauge   | `getSnapshot().getMin()`            | <units>^1^
| `max_<units>`                   | Gauge   | `getSnapshot().getMax()`            | <units>^1^
| `mean_<units>`                  | Gauge   | `getSnapshot().getMean()`           | <units>^1^
| `stddev_<units>`                | Gauge   | `getSnapshot().getStdDev()`         | <units>^1^
| `<units>_count`^2^              | Summary | `getCount()`                        | N/A
| `<units>{quantile="0.5"}`^2^    | Summary | `getSnapshot().getMedian()`         | <units>^1^
| `<units>{quantile="0.75"}`^2^   | Summary | `getSnapshot().get75thPercentile()` | <units>^1^
| `<units>{quantile="0.95"}`^2^   | Summary | `getSnapshot().get95thPercentile()` | <units>^1^
| `<units>{quantile="0.98"}`^2^   | Summary | `getSnapshot().get98thPercentile()` | <units>^1^
| `<units>{quantile="0.99"}`^2^   | Summary | `getSnapshot().get99thPercentile()` | <units>^1^
| `<units>{quantile="0.999"}`^2^  | Summary | `getSnapshot().get999thPercentile()`| <units>^1^
|===

^1^ The implementation is expected to convert the result returned by the `Histogram` into the base unit (if known). The `<unit>` represents the base metric unit and is named according to  <<OpenMetrics_units>>.

^2^ The `summary` type is a complex metric type for OpenMetrics which consists of the count and multiple quantile values.

.Example OpenMetrics text format for a Histogram with unit bytes.
[source, ruby]
----
# TYPE application_file_sizes_mean_bytes gauge
application_file_sizes_mean_bytes 4738.231
# TYPE application_file_sizes_max_bytes gauge
application_file_sizes_max_bytes 31716
# TYPE application_file_sizes_min_bytes gauge
application_file_sizes_min_bytes 180
# TYPE application_file_sizes_stddev_bytes gauge
application_file_sizes_stddev_bytes 1054.7343037063602
# TYPE application_file_sizes_bytes summary
# HELP application_file_sizes_bytes Users file size
application_file_sizes_bytes_count 2037
application_file_sizes_bytes{quantile="0.5"} 4201
application_file_sizes_bytes{quantile="0.75"} 6175
application_file_sizes_bytes{quantile="0.95"} 13560
application_file_sizes_bytes{quantile="0.98"} 29643
application_file_sizes_bytes{quantile="0.99"} 31716
application_file_sizes_bytes{quantile="0.999"} 31716
----


==== Timer OpenMetrics Text Format

`Timer` is a complex metric type comprised of multiple key/values. Each key will require a suffix to be appended to the metric name. The format is specified by the table below.

The `# HELP` description line is only required for the `summary` value as shown below.

.OpenMetrics text mapping for a Timer metric
[cols="2,1,2,1"]
|===
| Suffix{label}                   | TYPE    | Value (Timer method)                | Units

| `rate_per_second`               | Gauge   | `getMeanRate()`                     | PER_SECOND
| `one_min_rate_per_second`       | Gauge   | `getOneMinuteRate()`                | PER_SECOND
| `five_min_rate_per_second`      | Gauge   | `getFiveMinuteRate()`               | PER_SECOND
| `fifteen_min_rate_per_second`   | Gauge   | `getFifteenMinuteRate()`            | PER_SECOND
| `min_seconds`                   | Gauge   | `getSnapshot().getMin()`            | SECONDS^1^
| `max_seconds`                   | Gauge   | `getSnapshot().getMax()`            | SECONDS^1^
| `mean_seconds`                  | Gauge   | `getSnapshot().getMean()`           | SECONDS^1^
| `stddev_seconds`                | Gauge   | `getSnapshot().getStdDev()`         | SECONDS^1^
| `seconds_count`^2^              | Summary | `getCount()`                        | N/A
| `seconds{quantile="0.5"}`^2^    | Summary | `getSnapshot().getMedian()`         | SECONDS^1^
| `seconds{quantile="0.75"}`^2^   | Summary | `getSnapshot().get75thPercentile()` | SECONDS^1^
| `seconds{quantile="0.95"}`^2^   | Summary | `getSnapshot().get95thPercentile()` | SECONDS^1^
| `seconds{quantile="0.98"}`^2^   | Summary | `getSnapshot().get98thPercentile()` | SECONDS^1^
| `seconds{quantile="0.99"}`^2^   | Summary | `getSnapshot().get99thPercentile()` | SECONDS^1^
| `seconds{quantile="0.999"}`^2^  | Summary | `getSnapshot().get999thPercentile()`| SECONDS^1^
|===

^1^ The implementation is expected to convert the result returned by the `Timer` into seconds

^2^ The `summary` type is a complex metric type for OpenMetrics which consists of the count and multiple quantile values.

.Example OpenMetrics text format for a Timer
[source, ruby]
----
# TYPE application_response_time_rate_per_second gauge
application_response_time_rate_per_second  0.004292520715985437
# TYPE application_response_time_one_min_rate_per_second gauge
application_response_time_one_min_rate_per_second  2.794076465421066E-14
# TYPE application_response_time_five_min_rate_per_second  gauge
application_response_time_five_min_rate_per_second  4.800392614619373E-4
# TYPE application_response_time_fifteen_min_rate_per_second  gauge
application_response_time_fifteen_min_rate_per_second  0.01063191047532505
# TYPE application_response_time_mean_seconds gauge
application_response_time_mean_seconds 0.000415041
# TYPE application_response_time_max_seconds gauge
application_response_time_max_seconds 0.0005608694
# TYPE application_response_time_min_seconds gauge
application_response_time_min_seconds 0.000169916
# TYPE application_response_time_stddev_seconds gauge
application_response_time_stddev_seconds 0.000652907
# TYPE application_response_time_seconds summary
# HELP application_response_time_seconds Server response time for /index.html
application_response_time_seconds_count 80
application_response_time_seconds{quantile="0.5"} 0.0002933240
application_response_time_seconds{quantile="0.75"} 0.000344914
application_response_time_seconds{quantile="0.95"} 0.000543647
application_response_time_seconds{quantile="0.98"} 0.002706543
application_response_time_seconds{quantile="0.99"} 0.005608694
application_response_time_seconds{quantile="0.999"} 0.005608694
----

=== Security

It must be possible to secure the endpoints via the usual means. The definition of 'usual means' is in
this version of the specification implementation specific.

In case of a secured endpoint, accessing `/metrics` without valid credentials must return a `401 Unauthorized` header.

A server SHOULD implement TLS encryption by default.

It is allowed to ignore security for trusted origins (e.g. localhost)
